//
//  CartItemListRouter.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class CartItemListRouter : PresenterToRouterCartItemListProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = CartItemListViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterCartItemListProtocol & InteractorToPresenterCartItemListProtocol = CartItemListPresenter()
            let interactor : PresenterToIntetractorCartItemListProtocol = CartItemListInteractor()
            let router : PresenterToRouterCartItemListProtocol = CartItemListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
