//
//  VerificationRouter.swift
//  Mansour
//
//  Created SherifShokry on 11/25/19.
//  Copyright © 2019 BlueCrunch. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
import UIKit

class VerificationRouter : PresenterToRouterVerificationProtocol {
    
   
    static func createModule(request : RegisterRequest) -> UIViewController {
        
        let view = VerificationViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
        let presenter : ViewToPresenterVerificationProtocol & InteractorToPresenterVerificationProtocol = VerificationPresenter()
        let interactor : PresenterToIntetractorVerificationProtocol = VerificationInteractor()
        let router : PresenterToRouterVerificationProtocol = VerificationRouter()
        
        view.presenter = presenter
        presenter.interactor = interactor
        presenter.view = view
        presenter.signUpRequest = request
        presenter.setPhoneNumber(phone: request.phone)
        presenter.router = router
        interactor.presenter = presenter
        return view
    }
    
    static func createModule(phone : String) -> UIViewController {
          
          let view = VerificationViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
          let presenter : ViewToPresenterVerificationProtocol & InteractorToPresenterVerificationProtocol = VerificationPresenter()
          let interactor : PresenterToIntetractorVerificationProtocol = VerificationInteractor()
          let router : PresenterToRouterVerificationProtocol = VerificationRouter()
          
          view.presenter = presenter
          presenter.interactor = interactor
          presenter.view = view
          presenter.setPhoneNumber(phone: phone)
          presenter.router = router
          interactor.presenter = presenter
          return view
      }
    
   
    
    func openForgetPasswordSecondStepScreen(from sourceView: PresenterToViewVerificationProtocol?, phone : String,firebaseToken: String){
        
        let vc  = ResetPasswordRouter.createModule(phone: phone,firebaseToken: firebaseToken)
        
        if let sourceView = sourceView as? UIViewController {
            sourceView.present(vc,animated: true, completion: nil)
        }
    }
    
    
    func openAddAddress(from sourceView: PresenterToViewVerificationProtocol?) {
        let vc = AddAddressViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
        vc.openHomeScreen = true
        if let sourceView = sourceView as? UIViewController {
            sourceView.present(vc, animated: true, completion: nil)
        }
    }
    

    
}
