//
//  CartDetailsRouter.swift
//  Capsula
//
//  Created SherifShokry on 4/3/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class CartDetailsRouter : PresenterToRouterCartDetailsProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = CartDetailsViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterCartDetailsProtocol & InteractorToPresenterCartDetailsProtocol = CartDetailsPresenter()
            let interactor : PresenterToIntetractorCartDetailsProtocol = CartDetailsInteractor()
            let router : PresenterToRouterCartDetailsProtocol = CartDetailsRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    }
