//
//  SubCategoriesListProtocols.swift
//  Capsula
//
//  Created SherifShokry on 2/8/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
import Foundation
import UIKit

protocol ViewToPresenterSubCategoriesListProtocol: class {
    var view : PresenterToViewSubCategoriesListProtocol? {get set}
    var interactor : PresenterToIntetractorSubCategoriesListProtocol? {get set}
    var router : PresenterToRouterSubCategoriesListProtocol? {get set}
    var numberOfRows : Int { get }
    var  storeId : Int {get set}
    var  category : Category {set get}
    func configureSubCategoryCell(cell : CategoryCell , indexPath : IndexPath)
    func getSubCategoryData()
    func didSelectSubCategory(indexPath : IndexPath)
}

protocol PresenterToViewSubCategoriesListProtocol: class {
   func changeState(state : State)
}

protocol PresenterToIntetractorSubCategoriesListProtocol: class {
    var presenter: InteractorToPresenterSubCategoriesListProtocol? { get set }
    func getSubCategoriesData(categoryId : Int)
    func getSubCategoriesData(categoryId : Int, storeId: Int)
}

protocol PresenterToRouterSubCategoriesListProtocol: class  {
    static func createModule(category : Category) -> UIViewController
    static func createModule(category : Category, storeId : Int) -> UIViewController
    
    func openItemsScreen(from sourceView: PresenterToViewSubCategoriesListProtocol?,subCategory : Category)
     func openItemsScreen(from sourceView: PresenterToViewSubCategoriesListProtocol?, subCategory : Category,storeId : Int)
}

protocol InteractorToPresenterSubCategoriesListProtocol: class {
    func subCategoriesDataFetchedSuccessfully(subCategoriesResponse: [Category])
    func subCategoriesDataFailedToFetch(error : String)
}
