//
//  MainCartRouter.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class MainCartRouter : PresenterToRouterMainCartProtocol {
        
        static func createModule() -> UIViewController {
            let view = MainCartViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterMainCartProtocol & InteractorToPresenterMainCartProtocol = MainCartPresenter()
            let interactor : PresenterToIntetractorMainCartProtocol = MainCartInteractor()
            let router : PresenterToRouterMainCartProtocol = MainCartRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
        
        
        static func createModule(items : [Item]) -> UIViewController {
                   let view = MainCartViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
                   let presenter : ViewToPresenterMainCartProtocol & InteractorToPresenterMainCartProtocol = MainCartPresenter()
                   let interactor : PresenterToIntetractorMainCartProtocol = MainCartInteractor()
                   let router : PresenterToRouterMainCartProtocol = MainCartRouter()
                   
                   view.presenter = presenter
                   presenter.interactor = interactor
                   presenter.view = view
                   presenter.router = router
                   interactor.presenter = presenter
                   return view
               }
        
        
        
        
    }
