//
//  MainCartProtocols.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit


protocol ViewToPresenterMainCartProtocol: class {
    
    var view : PresenterToViewMainCartProtocol? {get set}
    var interactor : PresenterToIntetractorMainCartProtocol? {get set}
    var router : PresenterToRouterMainCartProtocol? {get set}
    
    
}

protocol PresenterToViewMainCartProtocol: class {
  
}

protocol PresenterToIntetractorMainCartProtocol: class {
    var presenter: InteractorToPresenterMainCartProtocol? { get set }
    
}

protocol PresenterToRouterMainCartProtocol: class  {
    static func createModule() -> UIViewController
    
}

protocol InteractorToPresenterMainCartProtocol: class {
   
}
