//
//  MainCartPresenter.swift
//  Capsula
//
//  Created SherifShokry on 3/29/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class MainCartPresenter : ViewToPresenterMainCartProtocol{
    
    var view: PresenterToViewMainCartProtocol?
    var interactor: PresenterToIntetractorMainCartProtocol?
    var router: PresenterToRouterMainCartProtocol?
   
}

extension MainCartPresenter : InteractorToPresenterMainCartProtocol {
    
 
}

