//
//  SearchItemRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/24/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class SearchItemRouter : PresenterToRouterSearchItemProtocol {
        
        static func createModule() -> UIViewController {
            
            let view = SearchItemViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterSearchItemProtocol & InteractorToPresenterSearchItemProtocol = SearchItemPresenter()
            let interactor : PresenterToIntetractorSearchItemProtocol = SearchItemInteractor()
            let router : PresenterToRouterSearchItemProtocol = SearchItemRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
        
        func openItemDetailsScreen(from sourceView: PresenterToViewSearchItemProtocol?, item: Item) {
           
            let vc = ItemDetailsRouter.createModule(item: item)
                                      if let sourceView = sourceView as? UIViewController {
                                          sourceView.present(vc,animated: true, completion: nil)
                                      }
        }
        
        
     
        
        
    }
