//
//  ResetPasswordProtocols.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit


protocol ViewToPresenterResetPasswordProtocol: class {
    
    var view : PresenterToViewResetPasswordProtocol? {get set}
    var interactor : PresenterToIntetractorResetPasswordProtocol? {get set}
    var router : PresenterToRouterResetPasswordProtocol? {get set}
    var phone : String { set get }
    var firebaseToken : String { set get }
    func resetPassword(password : String)
}

protocol PresenterToViewResetPasswordProtocol: class {
      func changeState(state : State)
     func showSuccessMsg(msg : String)
}

protocol PresenterToIntetractorResetPasswordProtocol: class {
    var presenter: InteractorToPresenterResetPasswordProtocol? { get set }
    func resetPassword(phone : String , password : String,firebaseToken: String)
    func resetDeliveryPassword(phone : String , password : String,firebaseToken: String)
}

protocol PresenterToRouterResetPasswordProtocol: class  {
    static func createModule(phone : String,firebaseToken: String) -> UIViewController
    
}

protocol InteractorToPresenterResetPasswordProtocol: class {
   func  passwordUpdatedSuccessfully()
   func  passwordFailedToUpdate(error : String)
}
