//
//  ResetPasswordPresenter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ResetPasswordPresenter : ViewToPresenterResetPasswordProtocol{
    
    var view: PresenterToViewResetPasswordProtocol?
    var interactor: PresenterToIntetractorResetPasswordProtocol?
    var router: PresenterToRouterResetPasswordProtocol?
    var phone = ""
    var firebaseToken = ""
    
    func resetPassword(password : String) {
        self.view?.changeState(state: .loading)
        
        let isDeliveryMan = UserDefaults.standard.bool(forKey: "isDelivery")
        if isDeliveryMan {
            self.interactor?.resetDeliveryPassword(phone: phone, password: password,firebaseToken: firebaseToken)
        }else{
            self.interactor?.resetPassword(phone: phone, password: password,firebaseToken: firebaseToken)
        }
    }
}

extension ResetPasswordPresenter : InteractorToPresenterResetPasswordProtocol {
    func passwordUpdatedSuccessfully() {
        self.view?.changeState(state: .ready)
        self.view?.showSuccessMsg(msg: Strings.shared.resetPasswordSuccessMsg)
    }
    
    func passwordFailedToUpdate(error: String) {
        self.view?.changeState(state: .error(error))
    }
    
}

