//
//  ResetPasswordRouter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
import UIKit

    class ResetPasswordRouter : PresenterToRouterResetPasswordProtocol {
        
        static func createModule(phone : String,firebaseToken: String) -> UIViewController {
            
            let view = ResetPasswordViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
            let presenter : ViewToPresenterResetPasswordProtocol & InteractorToPresenterResetPasswordProtocol = ResetPasswordPresenter()
            let interactor : PresenterToIntetractorResetPasswordProtocol = ResetPasswordInteractor()
            let router : PresenterToRouterResetPasswordProtocol = ResetPasswordRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            presenter.phone = phone
            presenter.firebaseToken = firebaseToken
            interactor.presenter = presenter
            return view
        }
    }
