//
//  CompleteProfileRouter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


    class CompleteProfileRouter : PresenterToRouterCompleteProfileProtocol {
        
        static func createModule(user : User,fromApple : Bool) -> UIViewController {
            
            let view = CompleteProfileViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
            let presenter : ViewToPresenterCompleteProfileProtocol & InteractorToPresenterCompleteProfileProtocol = CompleteProfilePresenter()
            let interactor : PresenterToIntetractorCompleteProfileProtocol = CompleteProfileInteractor()
            let router : PresenterToRouterCompleteProfileProtocol = CompleteProfileRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            presenter.user = user
            presenter.fromApple = fromApple
            interactor.presenter = presenter
            return view
        }
        
        func openVerificationScreen(from sourceView: PresenterToViewCompleteProfileProtocol?, request : RegisterRequest) {
               let vc = VerificationRouter.createModule(request: request)
               if let sourceView = sourceView as? UIViewController {
                   sourceView.present(vc,animated: true, completion: nil)
               }
           }
    }
