//
//  CompleteProfilePresenter.swift
//  Capsula
//
//  Created SherifShokry on 1/4/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class CompleteProfilePresenter : ViewToPresenterCompleteProfileProtocol{


    var view: PresenterToViewCompleteProfileProtocol?
    var interactor: PresenterToIntetractorCompleteProfileProtocol?
    var router: PresenterToRouterCompleteProfileProtocol?
    var user : User = User()
    var fromApple : Bool = false
    var registerRequest : RegisterRequest = RegisterRequest()

    func viewDidLoad(){
        self.view?.setUserData(user : user)
        if fromApple {
            self.view?.hideEmail()
        }
      
    }

    func setNameField(name : String) {
        registerRequest.name = name
    }
    
    
    func setEmailField(email : String) {
        registerRequest.email = email
    }
    
    func setPhoneFiled(phone : String) {
        registerRequest.phone = phone
    }
        
    func checkIfPhoneExist(phone: String) {
           self.view?.changeState(state: .loading)
        self.interactor?.checkIfPhoneExist(phone: phone, email: registerRequest.email)
      }

    
}

extension CompleteProfilePresenter : InteractorToPresenterCompleteProfileProtocol {
     func phoneNotExist() {
          self.view?.changeState(state: .ready)
          self.router?.openVerificationScreen(from: self.view,request : registerRequest)
      }
      
      func phoneIsExist() {
          self.view?.changeState(state: .error(Strings.shared.alreadyExist))
      }
}

