//
//  CategoriesListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


class CategoriesListRouter : PresenterToRouterCategoriesListProtocol {
   
    
    
        static func createModule() -> UIViewController {
            let view = CategoriesListViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterCategoriesListProtocol & InteractorToPresenterCategoriesListProtocol = CategoriesListPresenter()
            let interactor : PresenterToIntetractorCategoriesListProtocol = CategoriesListInteractor()
            let router : PresenterToRouterCategoriesListProtocol = CategoriesListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    
    
    static func createModule(storeId : Int) -> UIViewController {
             let view = CategoriesListViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
             let presenter : ViewToPresenterCategoriesListProtocol & InteractorToPresenterCategoriesListProtocol = CategoriesListPresenter()
             let interactor : PresenterToIntetractorCategoriesListProtocol = CategoriesListInteractor()
             let router : PresenterToRouterCategoriesListProtocol = CategoriesListRouter()
             
             view.presenter = presenter
             presenter.interactor = interactor
             presenter.storeId = storeId
             presenter.view = view
             presenter.router = router
             interactor.presenter = presenter
             return view
         }

    
    func openItemsScreen(from sourceView: PresenterToViewCategoriesListProtocol?, category: Category, storeId: Int) {
           let  vc = ItemsListRouter.createModule(category: category, storeId: storeId)
                     if let sourceView = sourceView as? UIViewController {
                         sourceView.present(vc,animated: true, completion: nil)
                     }
        
       }
        
        
    }
