//
//  StoresListRouter.swift
//  Capsula
//
//  Created SherifShokry on 2/7/20.
//  Copyright © 2020 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


class StoresListRouter : PresenterToRouterStoresListProtocol {
 
        
        static func createModule() -> UIViewController {
            let view = StoresListViewController.instantiateFromStoryBoard(appStoryBoard: .Home)
            let presenter : ViewToPresenterStoresListProtocol & InteractorToPresenterStoresListProtocol = StoresListPresenter()
            let interactor : PresenterToIntetractorStoresListProtocol = StoresListInteractor()
            let router : PresenterToRouterStoresListProtocol = StoresListRouter()
            
            view.presenter = presenter
            presenter.interactor = interactor
            presenter.view = view
            presenter.router = router
            interactor.presenter = presenter
            return view
        }
    
    
    func openCategoriesScreen(from sourceView: PresenterToViewStoresListProtocol?, storeId: Int) {
         let vc = CategoriesListRouter.createModule(storeId: storeId)
         if let sourceView = sourceView as? UIViewController {
                sourceView.present(vc,animated: true, completion: nil)
          }
     }
    
    }
