//
//  ForgetPasswordPresenter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

class ForgetPasswordPresenter : ViewToPresenterForgetPasswordProtocol{
    
    var view: PresenterToViewForgetPasswordProtocol?
    var interactor: PresenterToIntetractorForgetPasswordProtocol?
    var router: PresenterToRouterForgetPasswordProtocol?
    var phone = ""
      
      func checkIfPhoneExist(phone: String) {
            self.phone = phone
            self.view?.changeState(state: .loading)
        let isDeliveryMan = UserDefaults.standard.bool(forKey: "isDelivery")
        if isDeliveryMan {
            self.interactor?.checkIfDeliveryPhoneExist(phone: phone)
        }else{
           self.interactor?.checkIfPhoneExist(phone: phone)
        }
           
        }
    
    
    
}

extension ForgetPasswordPresenter : InteractorToPresenterForgetPasswordProtocol {
    
 func phoneNotExist() {
       self.view?.changeState(state: .error(Strings.shared.notExist))
 }
   
   func phoneIsExist() {
    self.view?.changeState(state: .ready)
    self.router?.openVerificationScreen(from: self.view, phone : phone)
  
   }
    
}

