//
//  ForgetPasswordRouter.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgetPasswordRouter : PresenterToRouterForgetPasswordProtocol {
    
    static func createModule() -> UIViewController {
        
        let view = ForgetPasswordViewController.instantiateFromStoryBoard(appStoryBoard: .PreLogin)
        let presenter : ViewToPresenterForgetPasswordProtocol & InteractorToPresenterForgetPasswordProtocol = ForgetPasswordPresenter()
        let interactor : PresenterToIntetractorForgetPasswordProtocol = ForgetPasswordInteractor()
        let router : PresenterToRouterForgetPasswordProtocol = ForgetPasswordRouter()
        
        view.presenter = presenter
        presenter.interactor = interactor
        presenter.view = view
        presenter.router = router
        interactor.presenter = presenter
        return view
    }
    
    func openVerificationScreen(from sourceView: PresenterToViewForgetPasswordProtocol?, phone: String) {
                    let vc = VerificationRouter.createModule(phone: phone)
                    if let sourceView = sourceView as? UIViewController {
                        sourceView.present(vc,animated: true, completion: nil)
                    }
    }
    
}
