//
//  ForgetPasswordInteractor.swift
//  Capsula
//
//  Created SherifShokry on 12/25/19.
//  Copyright © 2019 SherifShokry. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Moya
class ForgetPasswordInteractor : PresenterToIntetractorForgetPasswordProtocol {
    
    var presenter: InteractorToPresenterForgetPasswordProtocol?
    private let provider = MoyaProvider<UserDataSource>()
    private let deliveryProvider = MoyaProvider<DeliveryManRegistrationDataSource>()
      
    func checkIfPhoneExist(phone: String) {
        provider.request(.checkPhoneIsExist(phone, "")) { [weak self] result in
                   guard let self = self else { return }
                   switch result {
                   case .success(_):
                     self.presenter?.phoneIsExist()
                   case .failure(let error):
                    self.presenter?.phoneNotExist()
                }
               }
           }
    
    func checkIfDeliveryPhoneExist(phone: String) {
        deliveryProvider.request(.checkPhoneIsExist(phone, "")) { [weak self] result in
                    guard let self = self else { return }
                    switch result {
                    case .success(_):
                      self.presenter?.phoneIsExist()
                    case .failure(let error):
                     self.presenter?.phoneNotExist()
                 }
                }
            }
}

